//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class RefreshView:public drogon::DrTemplate<RefreshView>
{
public:
	RefreshView(){};
	virtual ~RefreshView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
